language: generic
sudo: required

services:
- docker

before-install:
- docker build -t 922611/dockerreact -f Dockerfile.dev .

script:
- docker run -e CI=true 922611/dockerreact npm run test

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerstarter"
  env: "Dockerstarter-env"
  bucketname: "elasticbeanstalk-us-east-1-269262753522"
  bucketpath: "dockerstarter"
  on:
       branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"