language: generic

sudo:required
services:
    - docker
    
before-install:
    - docker build -t 922611/dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true 922611/dockerreact npm run test